//initialize image variables
color = noone;
image_xscale = 1/25;
image_yscale = 1/25;
maxscale = 1/3;
//initialize behavior variables
xvel = 0;
yvel = -5;
combinable = true;
explosiveness = 15;
damage = 1;