//initialize image variables
color = noone;
image_xscale = 1/10;
image_yscale = 1/10;
maxscale = 10;
//initialize behavior variables
xvel = 0;
yvel = -6;
combinable = true;
explosiveness = 15;
damage = 1;